### ISSUE TITLE
Language Strings extraction from blade files

### ISSUE THREAD

**Issue by justie75** [vildanbina/laravel-auto-translation#2]
Hi, 

It would be nice to scan for language strings in blade files ex. __(), trans().
This would be better than only include the JSON lang files. 

When needed, i can help with a script.

**Comment by vildanbina** [comment]
Hi @justie75, thank you for the suggestion! I understand the value of scanning language strings in Blade files, and it’s a great idea. But at the moment, implementing this feature is not in my immediate plans due to time constraints.

That said, please feel free to contribute to this feature if you’d like. I’d be happy to review and support any contributions you make
